# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.

# The CMake executable.
CMAKE_COMMAND = /data/data/ru.iiec.cxxdroid/files/bin/cmake

# The command to remove a file.
RM = /data/data/ru.iiec.cxxdroid/files/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/storage/emulated/0/C++ projects/Cube"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/storage/emulated/0/C++ projects/Cube"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/storage/emulated/0/C++ projects/Cube/CMakeFiles" "/storage/emulated/0/C++ projects/Cube//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/storage/emulated/0/C++ projects/Cube/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

src/buffer_setter.o: src/buffer_setter.cxx.o
.PHONY : src/buffer_setter.o

# target to build an object file
src/buffer_setter.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/buffer_setter.cxx.o
.PHONY : src/buffer_setter.cxx.o

src/buffer_setter.i: src/buffer_setter.cxx.i
.PHONY : src/buffer_setter.i

# target to preprocess a source file
src/buffer_setter.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/buffer_setter.cxx.i
.PHONY : src/buffer_setter.cxx.i

src/buffer_setter.s: src/buffer_setter.cxx.s
.PHONY : src/buffer_setter.s

# target to generate assembly for a file
src/buffer_setter.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/buffer_setter.cxx.s
.PHONY : src/buffer_setter.cxx.s

src/main.o: src/main.cxx.o
.PHONY : src/main.o

# target to build an object file
src/main.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cxx.o
.PHONY : src/main.cxx.o

src/main.i: src/main.cxx.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cxx.i
.PHONY : src/main.cxx.i

src/main.s: src/main.cxx.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cxx.s
.PHONY : src/main.cxx.s

src/projection_matrix.o: src/projection_matrix.cxx.o
.PHONY : src/projection_matrix.o

# target to build an object file
src/projection_matrix.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/projection_matrix.cxx.o
.PHONY : src/projection_matrix.cxx.o

src/projection_matrix.i: src/projection_matrix.cxx.i
.PHONY : src/projection_matrix.i

# target to preprocess a source file
src/projection_matrix.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/projection_matrix.cxx.i
.PHONY : src/projection_matrix.cxx.i

src/projection_matrix.s: src/projection_matrix.cxx.s
.PHONY : src/projection_matrix.s

# target to generate assembly for a file
src/projection_matrix.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/projection_matrix.cxx.s
.PHONY : src/projection_matrix.cxx.s

src/quad.o: src/quad.cxx.o
.PHONY : src/quad.o

# target to build an object file
src/quad.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/quad.cxx.o
.PHONY : src/quad.cxx.o

src/quad.i: src/quad.cxx.i
.PHONY : src/quad.i

# target to preprocess a source file
src/quad.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/quad.cxx.i
.PHONY : src/quad.cxx.i

src/quad.s: src/quad.cxx.s
.PHONY : src/quad.s

# target to generate assembly for a file
src/quad.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/quad.cxx.s
.PHONY : src/quad.cxx.s

src/shader_compiler.o: src/shader_compiler.cxx.o
.PHONY : src/shader_compiler.o

# target to build an object file
src/shader_compiler.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/shader_compiler.cxx.o
.PHONY : src/shader_compiler.cxx.o

src/shader_compiler.i: src/shader_compiler.cxx.i
.PHONY : src/shader_compiler.i

# target to preprocess a source file
src/shader_compiler.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/shader_compiler.cxx.i
.PHONY : src/shader_compiler.cxx.i

src/shader_compiler.s: src/shader_compiler.cxx.s
.PHONY : src/shader_compiler.s

# target to generate assembly for a file
src/shader_compiler.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/shader_compiler.cxx.s
.PHONY : src/shader_compiler.cxx.s

src/window_initializer.o: src/window_initializer.cxx.o
.PHONY : src/window_initializer.o

# target to build an object file
src/window_initializer.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/window_initializer.cxx.o
.PHONY : src/window_initializer.cxx.o

src/window_initializer.i: src/window_initializer.cxx.i
.PHONY : src/window_initializer.i

# target to preprocess a source file
src/window_initializer.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/window_initializer.cxx.i
.PHONY : src/window_initializer.cxx.i

src/window_initializer.s: src/window_initializer.cxx.s
.PHONY : src/window_initializer.s

# target to generate assembly for a file
src/window_initializer.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/window_initializer.cxx.s
.PHONY : src/window_initializer.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... src/buffer_setter.o"
	@echo "... src/buffer_setter.i"
	@echo "... src/buffer_setter.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/projection_matrix.o"
	@echo "... src/projection_matrix.i"
	@echo "... src/projection_matrix.s"
	@echo "... src/quad.o"
	@echo "... src/quad.i"
	@echo "... src/quad.s"
	@echo "... src/shader_compiler.o"
	@echo "... src/shader_compiler.i"
	@echo "... src/shader_compiler.s"
	@echo "... src/window_initializer.o"
	@echo "... src/window_initializer.i"
	@echo "... src/window_initializer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

