# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.

# The CMake executable.
CMAKE_COMMAND = /data/data/ru.iiec.cxxdroid/files/bin/cmake

# The command to remove a file.
RM = /data/data/ru.iiec.cxxdroid/files/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/storage/emulated/0/C++ projects/Cube"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/storage/emulated/0/C++ projects/Cube"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/storage/emulated/0/C++ projects/Cube/CMakeFiles" "/storage/emulated/0/C++ projects/Cube//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/storage/emulated/0/C++ projects/Cube/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

src/buttons.o: src/buttons.cxx.o
.PHONY : src/buttons.o

# target to build an object file
src/buttons.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/buttons.cxx.o
.PHONY : src/buttons.cxx.o

src/buttons.i: src/buttons.cxx.i
.PHONY : src/buttons.i

# target to preprocess a source file
src/buttons.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/buttons.cxx.i
.PHONY : src/buttons.cxx.i

src/buttons.s: src/buttons.cxx.s
.PHONY : src/buttons.s

# target to generate assembly for a file
src/buttons.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/buttons.cxx.s
.PHONY : src/buttons.cxx.s

src/camera.o: src/camera.cxx.o
.PHONY : src/camera.o

# target to build an object file
src/camera.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/camera.cxx.o
.PHONY : src/camera.cxx.o

src/camera.i: src/camera.cxx.i
.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/camera.cxx.i
.PHONY : src/camera.cxx.i

src/camera.s: src/camera.cxx.s
.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/camera.cxx.s
.PHONY : src/camera.cxx.s

src/chunk_generator.o: src/chunk_generator.cxx.o
.PHONY : src/chunk_generator.o

# target to build an object file
src/chunk_generator.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/chunk_generator.cxx.o
.PHONY : src/chunk_generator.cxx.o

src/chunk_generator.i: src/chunk_generator.cxx.i
.PHONY : src/chunk_generator.i

# target to preprocess a source file
src/chunk_generator.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/chunk_generator.cxx.i
.PHONY : src/chunk_generator.cxx.i

src/chunk_generator.s: src/chunk_generator.cxx.s
.PHONY : src/chunk_generator.s

# target to generate assembly for a file
src/chunk_generator.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/chunk_generator.cxx.s
.PHONY : src/chunk_generator.cxx.s

src/cube_generator.o: src/cube_generator.cxx.o
.PHONY : src/cube_generator.o

# target to build an object file
src/cube_generator.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/cube_generator.cxx.o
.PHONY : src/cube_generator.cxx.o

src/cube_generator.i: src/cube_generator.cxx.i
.PHONY : src/cube_generator.i

# target to preprocess a source file
src/cube_generator.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/cube_generator.cxx.i
.PHONY : src/cube_generator.cxx.i

src/cube_generator.s: src/cube_generator.cxx.s
.PHONY : src/cube_generator.s

# target to generate assembly for a file
src/cube_generator.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/cube_generator.cxx.s
.PHONY : src/cube_generator.cxx.s

src/draw_functions.o: src/draw_functions.cxx.o
.PHONY : src/draw_functions.o

# target to build an object file
src/draw_functions.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/draw_functions.cxx.o
.PHONY : src/draw_functions.cxx.o

src/draw_functions.i: src/draw_functions.cxx.i
.PHONY : src/draw_functions.i

# target to preprocess a source file
src/draw_functions.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/draw_functions.cxx.i
.PHONY : src/draw_functions.cxx.i

src/draw_functions.s: src/draw_functions.cxx.s
.PHONY : src/draw_functions.s

# target to generate assembly for a file
src/draw_functions.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/draw_functions.cxx.s
.PHONY : src/draw_functions.cxx.s

src/image_loader.o: src/image_loader.cxx.o
.PHONY : src/image_loader.o

# target to build an object file
src/image_loader.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/image_loader.cxx.o
.PHONY : src/image_loader.cxx.o

src/image_loader.i: src/image_loader.cxx.i
.PHONY : src/image_loader.i

# target to preprocess a source file
src/image_loader.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/image_loader.cxx.i
.PHONY : src/image_loader.cxx.i

src/image_loader.s: src/image_loader.cxx.s
.PHONY : src/image_loader.s

# target to generate assembly for a file
src/image_loader.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/image_loader.cxx.s
.PHONY : src/image_loader.cxx.s

src/main.o: src/main.cxx.o
.PHONY : src/main.o

# target to build an object file
src/main.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cxx.o
.PHONY : src/main.cxx.o

src/main.i: src/main.cxx.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cxx.i
.PHONY : src/main.cxx.i

src/main.s: src/main.cxx.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cxx.s
.PHONY : src/main.cxx.s

src/matrix_math.o: src/matrix_math.cxx.o
.PHONY : src/matrix_math.o

# target to build an object file
src/matrix_math.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/matrix_math.cxx.o
.PHONY : src/matrix_math.cxx.o

src/matrix_math.i: src/matrix_math.cxx.i
.PHONY : src/matrix_math.i

# target to preprocess a source file
src/matrix_math.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/matrix_math.cxx.i
.PHONY : src/matrix_math.cxx.i

src/matrix_math.s: src/matrix_math.cxx.s
.PHONY : src/matrix_math.s

# target to generate assembly for a file
src/matrix_math.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/matrix_math.cxx.s
.PHONY : src/matrix_math.cxx.s

src/mesh_file.o: src/mesh_file.cxx.o
.PHONY : src/mesh_file.o

# target to build an object file
src/mesh_file.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/mesh_file.cxx.o
.PHONY : src/mesh_file.cxx.o

src/mesh_file.i: src/mesh_file.cxx.i
.PHONY : src/mesh_file.i

# target to preprocess a source file
src/mesh_file.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/mesh_file.cxx.i
.PHONY : src/mesh_file.cxx.i

src/mesh_file.s: src/mesh_file.cxx.s
.PHONY : src/mesh_file.s

# target to generate assembly for a file
src/mesh_file.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/mesh_file.cxx.s
.PHONY : src/mesh_file.cxx.s

src/program_file.o: src/program_file.cxx.o
.PHONY : src/program_file.o

# target to build an object file
src/program_file.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/program_file.cxx.o
.PHONY : src/program_file.cxx.o

src/program_file.i: src/program_file.cxx.i
.PHONY : src/program_file.i

# target to preprocess a source file
src/program_file.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/program_file.cxx.i
.PHONY : src/program_file.cxx.i

src/program_file.s: src/program_file.cxx.s
.PHONY : src/program_file.s

# target to generate assembly for a file
src/program_file.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/program_file.cxx.s
.PHONY : src/program_file.cxx.s

src/shader_compiler.o: src/shader_compiler.cxx.o
.PHONY : src/shader_compiler.o

# target to build an object file
src/shader_compiler.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/shader_compiler.cxx.o
.PHONY : src/shader_compiler.cxx.o

src/shader_compiler.i: src/shader_compiler.cxx.i
.PHONY : src/shader_compiler.i

# target to preprocess a source file
src/shader_compiler.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/shader_compiler.cxx.i
.PHONY : src/shader_compiler.cxx.i

src/shader_compiler.s: src/shader_compiler.cxx.s
.PHONY : src/shader_compiler.s

# target to generate assembly for a file
src/shader_compiler.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/shader_compiler.cxx.s
.PHONY : src/shader_compiler.cxx.s

src/user_input.o: src/user_input.cxx.o
.PHONY : src/user_input.o

# target to build an object file
src/user_input.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/user_input.cxx.o
.PHONY : src/user_input.cxx.o

src/user_input.i: src/user_input.cxx.i
.PHONY : src/user_input.i

# target to preprocess a source file
src/user_input.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/user_input.cxx.i
.PHONY : src/user_input.cxx.i

src/user_input.s: src/user_input.cxx.s
.PHONY : src/user_input.s

# target to generate assembly for a file
src/user_input.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/user_input.cxx.s
.PHONY : src/user_input.cxx.s

src/window_initializer.o: src/window_initializer.cxx.o
.PHONY : src/window_initializer.o

# target to build an object file
src/window_initializer.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/window_initializer.cxx.o
.PHONY : src/window_initializer.cxx.o

src/window_initializer.i: src/window_initializer.cxx.i
.PHONY : src/window_initializer.i

# target to preprocess a source file
src/window_initializer.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/window_initializer.cxx.i
.PHONY : src/window_initializer.cxx.i

src/window_initializer.s: src/window_initializer.cxx.s
.PHONY : src/window_initializer.s

# target to generate assembly for a file
src/window_initializer.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/window_initializer.cxx.s
.PHONY : src/window_initializer.cxx.s

src/world_matrices.o: src/world_matrices.cxx.o
.PHONY : src/world_matrices.o

# target to build an object file
src/world_matrices.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/world_matrices.cxx.o
.PHONY : src/world_matrices.cxx.o

src/world_matrices.i: src/world_matrices.cxx.i
.PHONY : src/world_matrices.i

# target to preprocess a source file
src/world_matrices.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/world_matrices.cxx.i
.PHONY : src/world_matrices.cxx.i

src/world_matrices.s: src/world_matrices.cxx.s
.PHONY : src/world_matrices.s

# target to generate assembly for a file
src/world_matrices.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/world_matrices.cxx.s
.PHONY : src/world_matrices.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... src/buttons.o"
	@echo "... src/buttons.i"
	@echo "... src/buttons.s"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/chunk_generator.o"
	@echo "... src/chunk_generator.i"
	@echo "... src/chunk_generator.s"
	@echo "... src/cube_generator.o"
	@echo "... src/cube_generator.i"
	@echo "... src/cube_generator.s"
	@echo "... src/draw_functions.o"
	@echo "... src/draw_functions.i"
	@echo "... src/draw_functions.s"
	@echo "... src/image_loader.o"
	@echo "... src/image_loader.i"
	@echo "... src/image_loader.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/matrix_math.o"
	@echo "... src/matrix_math.i"
	@echo "... src/matrix_math.s"
	@echo "... src/mesh_file.o"
	@echo "... src/mesh_file.i"
	@echo "... src/mesh_file.s"
	@echo "... src/program_file.o"
	@echo "... src/program_file.i"
	@echo "... src/program_file.s"
	@echo "... src/shader_compiler.o"
	@echo "... src/shader_compiler.i"
	@echo "... src/shader_compiler.s"
	@echo "... src/user_input.o"
	@echo "... src/user_input.i"
	@echo "... src/user_input.s"
	@echo "... src/window_initializer.o"
	@echo "... src/window_initializer.i"
	@echo "... src/window_initializer.s"
	@echo "... src/world_matrices.o"
	@echo "... src/world_matrices.i"
	@echo "... src/world_matrices.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

